config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'sessions'
  }
 
  resources :tasks do
    resources :notes, only: [:create], controller: 'tasks/notes'
  end  
    resources :categories

  root "tasks#index"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  #root 'tasks#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %br
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navbar.html.haml
-# app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark-blue.px-5
  %a.navbar-brand{ href: root_path }
    = image_tag 'logo.png', class: 'd-inline-block align-top', width: 85
  %button.navbar-toggler{"aria-controls" => "navbarNavDropdown", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarNavDropdown", "data-bs-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarNavDropdown.collapse.navbar-collapse
    %ul.navbar-nav
      %li.nav-item.active
        %a.nav-link{ href: root_path } Inicio
        %span.sr-only (current)
      %li.nav-item
        %a.nav-link{ href: categories_path } Categorías
  = link_to 'Crear Tarea', new_task_path, class: 'btn btn-light ml-2'
  .dropdown.dropdown-user
    %buttonbtn.btn-outline-dark.dropdown-toggle#userMenu{"aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-toggle" => "dropdown", "data-bs-display" => "static"}
      = image_tag "https://robohash.org/#{current_user.email}?size=38x38"
    .dropdown-menu.dropdown-menu-lg-end{"aria-labelledby" => "userMenu"}
      .dropdown-item.small.text-end= current_user.email
      .dropdown-divider
      = link_to destroy_user_session_path, data: { "turbo-method": :delete }, class: 'dropdown-item' do
        .fas.fa-sign-out
        Cerrar sesión

 
 

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Organizador
  %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_link_tag "application", "data-turbo-track": "reload"
  = javascript_importmap_tags
%body
  = render 'layouts/navbar'
.container.mt-4.pb-4
  .main-flash-messages
    = render 'layouts/messages'
  = yield

app/views/layouts/devise.html.haml
!!!
%html
%head
  %title Organizador
  %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_link_tag "application", "data-turbo-track": "reload"
  = javascript_importmap_tags
%body.bg-dark.text-white
.container.mt-4.pb-4
  .main-flash-messages
    = render 'layouts/messages'
  .w-25.m-auto
    = yield